<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class DataMesin extends Seeder
{
    public function run()
    {
        $data = [
            [
                'area' => 'KK1A',
                'jarum' => 'JC120',
                'total_mc' => 2,
                'brand' => 'Lonati 120 OPENTOE',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK1A',
                'jarum' => 'TJ120',
                'total_mc' => 27,
                'brand' => 'Lonati 120 OPENTOE',
                'mesin_jalan' => 17,
            ],
            [
                'area' => 'KK1A',
                'jarum' => 'JC120',
                'total_mc' => 4,
                'brand' => 'Lonati 120 AUTOLINK',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK1A',
                'jarum' => 'TJ120',
                'total_mc' => 15,
                'brand' => 'Lonati 120 AUTOLINK',
                'mesin_jalan' => 12,
            ],
            [
                'area' => 'KK1A',
                'jarum' => 'JC144',
                'total_mc' => 59,
                'brand' => 'Lonati 144 OPENTOE',
                'mesin_jalan' => 53,
            ],
            [
                'area' => 'KK1A',
                'jarum' => 'TJ144',
                'total_mc' => 30,
                'brand' => 'Lonati 144 OPENTOE',
                'mesin_jalan' => 29,
            ],
            [
                'area' => 'KK1A',
                'jarum' => 'JC144',
                'total_mc' => 17,
                'brand' => 'Lonati 144 AUTOLINK',
                'mesin_jalan' => 13,
            ],
            [
                'area' => 'KK1A',
                'jarum' => 'TJ144',
                'total_mc' => 67,
                'brand' => 'Lonati 144 AUTOLINK',
                'mesin_jalan' => 57,
            ],
            [
                'area' => 'KK1A',
                'jarum' => 'JC168',
                'total_mc' => 154,
                'brand' => 'Lonati 168 AUTOLINK',
                'mesin_jalan' => 112,
            ],
            [
                'area' => 'KK1A',
                'jarum' => 'TJ168',
                'total_mc' => 9,
                'brand' => 'Lonati 168 AUTOLINK',
                'mesin_jalan' => 5,
            ],
            [
                'area' => 'KK1B',
                'jarum' => 'JC120',
                'total_mc' => 152,
                'brand' => 'ROSSO',
                'mesin_jalan' => 146,
            ],
            [
                'area' => 'KK1B',
                'jarum' => 'TJ120',
                'total_mc' => 0,
                'brand' => 'ROSSO',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK1B',
                'jarum' => 'JC144',
                'total_mc' => 172,
                'brand' => 'ROSSO',
                'mesin_jalan' => 162,
            ],
            [
                'area' => 'KK1B',
                'jarum' => 'TJ144',
                'total_mc' => 0,
                'brand' => 'ROSSO',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK1B',
                'jarum' => 'JC168',
                'total_mc' => 0,
                'brand' => 'ROSSO',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK2A',
                'jarum' => 'JC120',
                'total_mc' => 68,
                'brand' => 'DAKONG',
                'mesin_jalan' => 53,
            ],[
                'area' => 'KK2A',
                'jarum' => 'JC144',
                'total_mc' => 223,
                'brand' => 'DAKONG',
                'mesin_jalan' => 223,
            ],
            [
                'area' => 'KK2A',
                'jarum' => 'JC120',
                'total_mc' => 45,
                'brand' => 'ROSSO',
                'mesin_jalan' => 45,
            ],
            [
                'area' => 'KK2A',
                'jarum' => 'JC144',
                'total_mc' => 134,
                'brand' => 'ROSSO',
                'mesin_jalan' => 134,
            ],
            [
                'area' => 'KK2B',
                'jarum' => 'JC120',
                'total_mc' => 160,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK2C',
                'jarum' => 'JC144',
                'total_mc' => 400,
                'brand' => 'DAKONG',
                'mesin_jalan' => 343,
            ],
            [
                'area' => 'KK5',
                'jarum' => 'JC144',
                'total_mc' => 100,
                'brand' => 'DAKONG',
                'mesin_jalan' => 91,
            ],
            [
                'area' => 'KK5',
                'jarum' => 'JC168',
                'total_mc' => 200,
                'brand' => 'DAKONG',
                'mesin_jalan' => 169,
            ],
            [
                'area' => 'KK7K',
                'jarum' => 'JC120',
                'total_mc' => 0,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK7K',
                'jarum' => 'JC144',
                'total_mc' => 148,
                'brand' => 'DAKONG',
                'mesin_jalan' => 131,
            ],
            [
                'area' => 'KK7K',
                'jarum' => 'JC168',
                'total_mc' => 68,
                'brand' => 'DAKONG',
                'mesin_jalan' => 23,
            ],
            [
                'area' => 'KK7K',
                'jarum' => 'TJ120',
                'total_mc' => 1,
                'brand' => 'Lonati 120 AUTOLINK',
                'mesin_jalan' => 1,
            ],
            [
                'area' => 'KK7K',
                'jarum' => 'TJ144',
                'total_mc' => 14,
                'brand' => 'Lonati 144 AUTOLINK',
                'mesin_jalan' => 11,
            ],
            [
                'area' => 'KK7K',
                'jarum' => 'TJ168',
                'total_mc' => 5,
                'brand' => 'Lonati 168 AUTOLINK',
                'mesin_jalan' => 2,
            ],
            [
                'area' => 'KK7L',
                'jarum' => 'JC96',
                'total_mc' => 0,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK7L',
                'jarum' => 'TJ96',
                'total_mc' => 0,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK7L',
                'jarum' => 'JC108',
                'total_mc' => 0,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK7L',
                'jarum' => 'TJ108',
                'total_mc' => 0,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK7L',
                'jarum' => 'TJ120',
                'total_mc' => 0,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK7L',
                'jarum' => 'JC144',
                'total_mc' => 72,
                'brand' => 'DAKONG',
                'mesin_jalan' => 68,
            ],
            [
                'area' => 'KK7L',
                'jarum' => 'JC96',
                'total_mc' => 3,
                'brand' => 'ROSSO',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK7L',
                'jarum' => 'JC108',
                'total_mc' => 12,
                'brand' => 'ROSSO',
                'mesin_jalan' => 1,
            ],
            [
                'area' => 'KK7L',
                'jarum' => 'TJ108',
                'total_mc' => 0,
                'brand' => 'ROSSO',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK7L',
                'jarum' => 'JC120',
                'total_mc' => 12,
                'brand' => 'ROSSO',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK7L',
                'jarum' => 'TJ120',
                'total_mc' => 8,
                'brand' => 'ROSSO',
                'mesin_jalan' => 7,
            ],
            [
                'area' => 'KK7L',
                'jarum' => 'JC168',
                'total_mc' => 0,
                'brand' => 'ROSSO',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK7L',
                'jarum' => 'JC144',
                'total_mc' => 10,
                'brand' => 'ROSSO',
                'mesin_jalan' => 10,
            ],
            [
                'area' => 'KK8D',
                'jarum' => 'JC144',
                'total_mc' => 158,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK8D',
                'jarum' => 'DC108',
                'total_mc' => 40,
                'brand' => 'MECHANIC',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK8D',
                'jarum' => 'DC124',
                'total_mc' => 20,
                'brand' => 'MECHANIC',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK8D',
                'jarum' => 'DC144LDF',
                'total_mc' => 4,
                'brand' => 'LONATI 952 LDF',
                'mesin_jalan' => 4,
            ],
            [
                'area' => 'KK8D',
                'jarum' => 'DC144LSF',
                'total_mc' => 52,
                'brand' => 'LONATI 956 LSF',
                'mesin_jalan' => 42,
            ],
            [
                'area' => 'KK8D',
                'jarum' => 'DC168LDF',
                'total_mc' => 34,
                'brand' => 'LONATI 952 LDF',
                'mesin_jalan' => 3,
            ],
            [
                'area' => 'KK8D',
                'jarum' => 'DC168LSF',
                'total_mc' => 2,
                'brand' => 'LONATI 956 LSF',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK8D',
                'jarum' => 'DC84 (DC168LSF : 2)',
                'total_mc' => 0,
                'brand' => 'LONATI 956 LSF',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK8D',
                'jarum' => 'DC84L',
                'total_mc' => 5,
                'brand' => 'LONATI 956 LSF',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK8D',
                'jarum' => 'DC168LSF',
                'total_mc' => 2,
                'brand' => 'AURORA SF',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK8F',
                'jarum' => 'JC120',
                'total_mc' => 0,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK8F',
                'jarum' => 'JC144',
                'total_mc' => 113,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK8F',
                'jarum' => 'JC168',
                'total_mc' => 0,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK9',
                'jarum' => 'JC120',
                'total_mc' => 0,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK9',
                'jarum' => 'JC144',
                'total_mc' => 0,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK10',
                'jarum' => 'JC120',
                'total_mc' => 64,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK10',
                'jarum' => 'JC144',
                'total_mc' => 145,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK10',
                'jarum' => 'JC144',
                'total_mc' => 128,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK11',
                'jarum' => 'JC144',
                'total_mc' => 100,
                'brand' => 'ROSSO',
                'mesin_jalan' => 100,
            ],
            [
                'area' => 'KK11',
                'jarum' => 'TJ144',
                'total_mc' => 0,
                'brand' => 'ROSSO',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK11',
                'jarum' => 'JC120',
                'total_mc' => 0,
                'brand' => 'ROSSO',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK11',
                'jarum' => 'DC144LDF',
                'total_mc' => 20,
                'brand' => 'LONATI 952 LDF',
                'mesin_jalan' => 20,
            ],
            [
                'area' => 'KK8J',
                'jarum' => '10G84N',
                'total_mc' => 33,
                'brand' => 'GLOVES',
                'mesin_jalan' => 33,
            ],
            [
                'area' => 'KK8J',
                'jarum' => '10G92N',
                'total_mc' => 44,
                'brand' => 'GLOVES',
                'mesin_jalan' => 23,
            ],
            [
                'area' => 'KK8J',
                'jarum' => '10G106N',
                'total_mc' => 301,
                'brand' => 'GLOVES',
                'mesin_jalan' => 266,
            ],
            [
                'area' => 'KK8J',
                'jarum' => '10G116N',
                'total_mc' => 48,
                'brand' => 'GLOVES',
                'mesin_jalan' => 11,
            ],
            [
                'area' => 'KK8J',
                'jarum' => '10G126N',
                'total_mc' => 4,
                'brand' => 'GLOVES',
                'mesin_jalan' => 4,
            ],
            [
                'area' => 'KK8J',
                'jarum' => '13G',
                'total_mc' => 10,
                'brand' => 'GLOVES',
                'mesin_jalan' => 0,
            ],
            [
                'area' => 'KK8J',
                'jarum' => '240N',
                'total_mc' => 7,
                'brand' => 'GLOVES',
                'mesin_jalan' => 7,
            ],
            [
                'area' => 'KK8J',
                'jarum' => 'POM-POM',
                'total_mc' => 1,
                'brand' => 'GLOVES',
                'mesin_jalan' => 1,
            ],


        ];
        $this->db->table('data_mesin')->insertBatch($data);
    }
}
