<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class DataMesin extends Seeder
{
    public function run()
    {
        $data = [
            [
                'area' => 'KK1A',
                'jarum' => 'JC120',
                'total_mc' => 2,
                'brand' => 'Lonati 120 OPENTOE',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Child Comp N120',
            ],
            [
                'area' => 'KK1A',
                'jarum' => 'TJ120',
                'total_mc' => 27,
                'brand' => 'Lonati 120 OPENTOE',
                'mesin_jalan' => 17,
                'aliasjarum' => 'Child Comp N120 Sp',
            ],
            [
                'area' => 'KK1A',
                'jarum' => 'JC120',
                'total_mc' => 4,
                'brand' => 'Lonati 120 AUTOLINK',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Child Comp N120',
            ],
            [
                'area' => 'KK1A',
                'jarum' => 'TJ120',
                'total_mc' => 15,
                'brand' => 'Lonati 120 AUTOLINK',
                'mesin_jalan' => 12,
                'aliasjarum' => 'Child Comp N120 Sp',
            ],
            [
                'area' => 'KK1A',
                'jarum' => 'JC144',
                'total_mc' => 59,
                'brand' => 'Lonati 144 OPENTOE',
                'mesin_jalan' => 53,
                'aliasjarum' => 'Ladies Comp N144',
            ],
            [
                'area' => 'KK1A',
                'jarum' => 'TJ144',
                'total_mc' => 30,
                'brand' => 'Lonati 144 OPENTOE',
                'mesin_jalan' => 29,
                'aliasjarum' => 'Ladies Comp N144 Sp',
            ],
            [
                'area' => 'KK1A',
                'jarum' => 'JC144',
                'total_mc' => 17,
                'brand' => 'Lonati 144 AUTOLINK',
                'mesin_jalan' => 13,
                'aliasjarum' => 'Ladies Comp N144',
            ],
            [
                'area' => 'KK1A',
                'jarum' => 'TJ144',
                'total_mc' => 67,
                'brand' => 'Lonati 144 AUTOLINK',
                'mesin_jalan' => 57,
                'aliasjarum' => 'Ladies Comp N144 Sp',
            ],
            [
                'area' => 'KK1A',
                'jarum' => 'JC168',
                'total_mc' => 154,
                'brand' => 'Lonati 168 AUTOLINK',
                'mesin_jalan' => 112,
                'aliasjarum' => 'Mens Comp N168',
            ],
            [
                'area' => 'KK1A',
                'jarum' => 'TJ168',
                'total_mc' => 9,
                'brand' => 'Lonati 168 AUTOLINK',
                'mesin_jalan' => 5,
                'aliasjarum' => 'Mens Comp N168 Sp',
            ],
            [
                'area' => 'KK1B',
                'jarum' => 'JC120',
                'total_mc' => 152,
                'brand' => 'ROSSO',
                'mesin_jalan' => 146,
                'aliasjarum' => 'Child Comp N120',
            ],
            [
                'area' => 'KK1B',
                'jarum' => 'TJ120',
                'total_mc' => 0,
                'brand' => 'ROSSO',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Child Comp N120 Sp',
            ],
            [
                'area' => 'KK1B',
                'jarum' => 'JC144',
                'total_mc' => 172,
                'brand' => 'ROSSO',
                'mesin_jalan' => 162,
                'aliasjarum' => 'Ladies Comp N144',
            ],
            [
                'area' => 'KK1B',
                'jarum' => 'TJ144',
                'total_mc' => 0,
                'brand' => 'ROSSO',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Ladies Comp N144 Sp',
            ],
            [
                'area' => 'KK1B',
                'jarum' => 'JC168',
                'total_mc' => 0,
                'brand' => 'ROSSO',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Mens Comp N168',
            ],
            [
                'area' => 'KK2A',
                'jarum' => 'JC120',
                'total_mc' => 68,
                'brand' => 'DAKONG',
                'mesin_jalan' => 53,
                'aliasjarum' => 'Child Comp N120',
            ],             
            [
                'area' => 'KK2A',
                'jarum' => 'JC120',
                'total_mc' => 45,
                'brand' => 'ROSSO',
                'mesin_jalan' => 45,
                'aliasjarum' => 'Child Comp N120',
            ],
            [
                'area' => 'KK2A',
                'jarum' => 'JC144',
                'total_mc' => 134,
                'brand' => 'ROSSO',
                'mesin_jalan' => 134,
                'aliasjarum' => 'Ladies Comp N144',
            ],
            [
                'area' => 'KK2B',
                'jarum' => 'JC120',
                'total_mc' => 160,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Child Comp N120',
            ],
            [
                'area' => 'KK2C',
                'jarum' => 'JC144',
                'total_mc' => 400,
                'brand' => 'DAKONG',
                'mesin_jalan' => 343,
                'aliasjarum' => 'Ladies Comp N144',
            ],
            [
                'area' => 'KK5',
                'jarum' => 'JC144',
                'total_mc' => 100,
                'brand' => 'DAKONG',
                'mesin_jalan' => 91,
                'aliasjarum' => 'Ladies Comp N144',
            ],
            [
                'area' => 'KK5',
                'jarum' => 'JC168',
                'total_mc' => 200,
                'brand' => 'DAKONG',
                'mesin_jalan' => 169,
                'aliasjarum' => 'Mens Comp N168',
            ],
            [
                'area' => 'KK7K',
                'jarum' => 'JC120',
                'total_mc' => 0,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Child Comp N120',
            ],
            [
                'area' => 'KK7K',
                'jarum' => 'JC144',
                'total_mc' => 148,
                'brand' => 'DAKONG',
                'mesin_jalan' => 131,
                'aliasjarum' => 'Ladies Comp N144',
            ],
            [
                'area' => 'KK7K',
                'jarum' => 'JC168',
                'total_mc' => 68,
                'brand' => 'DAKONG',
                'mesin_jalan' => 23,
                'aliasjarum' => 'Mens Comp N168',
            ],
            [
                'area' => 'KK7K',
                'jarum' => 'TJ120',
                'total_mc' => 1,
                'brand' => 'Lonati 120 AUTOLINK',
                'mesin_jalan' => 1,
                'aliasjarum' => 'Child Comp N120 Sp',
            ],
            [
                'area' => 'KK7K',
                'jarum' => 'TJ144',
                'total_mc' => 14,
                'brand' => 'Lonati 144 AUTOLINK',
                'mesin_jalan' => 11,
                'aliasjarum' => 'Ladies Comp N144 Sp',
            ],
            [
                'area' => 'KK7K',
                'jarum' => 'TJ168',
                'total_mc' => 5,
                'brand' => 'Lonati 168 AUTOLINK',
                'mesin_jalan' => 2,
                'aliasjarum' => 'Mens Comp N168 Sp',
            ],
            [
                'area' => 'KK7L',
                'jarum' => 'JC96',
                'total_mc' => 0,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Baby Comp N96',
            ],
            [
                'area' => 'KK7L',
                'jarum' => 'TJ96',
                'total_mc' => 0,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Baby Comp N96 Sp',
            ],
            [
                'area' => 'KK7L',
                'jarum' => 'JC108',
                'total_mc' => 0,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Baby Comp N108',
            ],
            [
                'area' => 'KK7L',
                'jarum' => 'TJ108',
                'total_mc' => 0,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Baby Comp N108 Sp',
            ],
            [
                'area' => 'KK7L',
                'jarum' => 'TJ120',
                'total_mc' => 0,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Child Comp N120 Sp',
            ],
            [
                'area' => 'KK7L',
                'jarum' => 'JC144',
                'total_mc' => 72,
                'brand' => 'DAKONG',
                'mesin_jalan' => 68,
                'aliasjarum' => 'Ladies Comp N144',
            ],
            [
                'area' => 'KK7L',
                'jarum' => 'JC96',
                'total_mc' => 3,
                'brand' => 'ROSSO',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Baby Comp N96',
            ],
            [
                'area' => 'KK7L',
                'jarum' => 'JC108',
                'total_mc' => 12,
                'brand' => 'ROSSO',
                'mesin_jalan' => 1,
                'aliasjarum' => 'Baby Comp N108',
            ],
            [
                'area' => 'KK7L',
                'jarum' => 'TJ108',
                'total_mc' => 0,
                'brand' => 'ROSSO',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Baby Comp N108 Sp',
            ],
            [
                'area' => 'KK7L',
                'jarum' => 'JC120',
                'total_mc' => 12,
                'brand' => 'ROSSO',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Ladies Comp N120',
            ],
            [
                'area' => 'KK7L',
                'jarum' => 'TJ120',
                'total_mc' => 8,
                'brand' => 'ROSSO',
                'mesin_jalan' => 7,
                'aliasjarum' => 'Ladies Comp N120 Sp',
            ],
            [
                'area' => 'KK7L',
                'jarum' => 'JC168',
                'total_mc' => 0,
                'brand' => 'ROSSO',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Mens Comp N168',
            ],
            [
                'area' => 'KK7L',
                'jarum' => 'JC144',
                'total_mc' => 10,
                'brand' => 'ROSSO',
                'mesin_jalan' => 10,
                'aliasjarum' => 'Ladies Comp N144',
            ],
            [
                'area' => 'KK8D',
                'jarum' => 'JC144',
                'total_mc' => 158,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Ladies Comp N144',
            ],
            [
                'area' => 'KK8D',
                'jarum' => 'DC108',
                'total_mc' => 40,
                'brand' => 'MECHANIC',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Double Cylinder N108',
            ],
            [
                'area' => 'KK8D',
                'jarum' => 'DC124',
                'total_mc' => 20,
                'brand' => 'MECHANIC',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Double Cylinder N124',
            ],
            [
                'area' => 'KK8D',
                'jarum' => 'DC144LDF',
                'total_mc' => 4,
                'brand' => 'LONATI 952 LDF',
                'mesin_jalan' => 4,
                'aliasjarum' => 'DC N144 2 Feed',
            ],
            [
                'area' => 'KK8D',
                'jarum' => 'DC144LSF',
                'total_mc' => 52,
                'brand' => 'LONATI 956 LSF',
                'mesin_jalan' => 42,
                'aliasjarum' => 'DC N144 Links-Links',
            ],
            [
                'area' => 'KK8D',
                'jarum' => 'DC168LDF',
                'total_mc' => 34,
                'brand' => 'LONATI 952 LDF',
                'mesin_jalan' => 3,
                'aliasjarum' => 'DC N168 2 Feed',
            ],
            [
                'area' => 'KK8D',
                'jarum' => 'DC168LSF',
                'total_mc' => 2,
                'brand' => 'LONATI 956 LSF',
                'mesin_jalan' => 0,
                'aliasjarum' => 'DC N168 Links-Links',
            ],
            [
                'area' => 'KK8D',
                'jarum' => 'DC168LSF:2',
                'total_mc' => 0,
                'brand' => 'LONATI 956 LSF',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Double Cylinder N84L (DC168L:2)',
            ],
            [
                'area' => 'KK8D',
                'jarum' => 'DC84L',
                'total_mc' => 5,
                'brand' => 'LONATI 956 LSF',
                'mesin_jalan' => 0,
                'aliasjarum' => 'DC 84N Link Bravo',
            ],
            [
                'area' => 'KK8D',
                'jarum' => 'DC168LSF',
                'total_mc' => 2,
                'brand' => 'AURORA SF',
                'mesin_jalan' => 0,
                'aliasjarum' => 'DC N168 Links-Links',
            ],
            [
                'area' => 'KK8F',
                'jarum' => 'JC120',
                'total_mc' => 0,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Child Comp N120',
            ],
            [
                'area' => 'KK8F',
                'jarum' => 'JC144',
                'total_mc' => 113,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Ladies Comp N144',
            ],
            [
                'area' => 'KK8F',
                'jarum' => 'JC168',
                'total_mc' => 0,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Mens Comp N168',
            ],
            [
                'area' => 'KK9',
                'jarum' => 'JC120',
                'total_mc' => 0,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Child Comp N120',
            ],
            [
                'area' => 'KK9',
                'jarum' => 'JC144',
                'total_mc' => 0,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Ladies Comp N144',
            ],
            [
                'area' => 'KK10',
                'jarum' => 'JC120',
                'total_mc' => 64,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Child Comp N120',
            ],
            [
                'area' => 'KK10',
                'jarum' => 'JC144',
                'total_mc' => 145,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Ladies Comp N144',
            ],
            [
                'area' => 'KK10',
                'jarum' => 'JC144',
                'total_mc' => 128,
                'brand' => 'DAKONG',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Ladies Comp N144',
            ],
            [
                'area' => 'KK11',
                'jarum' => 'JC144',
                'total_mc' => 100,
                'brand' => 'ROSSO',
                'mesin_jalan' => 100,
                'aliasjarum' => 'Ladies Comp N144',
            ],
            [
                'area' => 'KK11',
                'jarum' => 'TJ144',
                'total_mc' => 0,
                'brand' => 'ROSSO',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Ladies Comp N144 Sp',
            ],
            [
                'area' => 'KK11',
                'jarum' => 'JC120',
                'total_mc' => 0,
                'brand' => 'ROSSO',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Ladies Comp N120',
            ],
            [
                'area' => 'KK11',
                'jarum' => 'DC144LDF',
                'total_mc' => 20,
                'brand' => 'LONATI 952 LDF',
                'mesin_jalan' => 20,
                'aliasjarum' => 'DC N144 Feed (Okamoto)',
            ],
            [
                'area' => 'KK8J',
                'jarum' => '10G84N',
                'total_mc' => 33,
                'brand' => 'GLOVES',
                'mesin_jalan' => 33,
                'aliasjarum' => 'Baby 10G (84N)',
            ],
            [
                'area' => 'KK8J',
                'jarum' => '10G92N',
                'total_mc' => 44,
                'brand' => 'GLOVES',
                'mesin_jalan' => 23,
                'aliasjarum' => 'Baby 10G (92N)',
            ],
            [
                'area' => 'KK8J',
                'jarum' => '10G106N',
                'total_mc' => 301,
                'brand' => 'GLOVES',
                'mesin_jalan' => 266,
                'aliasjarum' => 'Child/Ladies 10G (106N)',
            ],
            [
                'area' => 'KK8J',
                'jarum' => '10G116N',
                'total_mc' => 48,
                'brand' => 'GLOVES',
                'mesin_jalan' => 11,
                'aliasjarum' => 'Ladies/Mens 10G (116N)',
                
            ],
            [
                'area' => 'KK8J',
                'jarum' => '10G126N',
                'total_mc' => 4,
                'brand' => 'GLOVES',
                'mesin_jalan' => 4,
                'aliasjarum' => 'Ladies/Mens 10G (126N)',
            ],
            [
                'area' => 'KK8J',
                'jarum' => '13G',
                'total_mc' => 10,
                'brand' => 'GLOVES',
                'mesin_jalan' => 0,
                'aliasjarum' => 'Ladies/Mens 13G',
            ],
            [
                'area' => 'KK8J',
                'jarum' => '240N',
                'total_mc' => 7,
                'brand' => 'GLOVES',
                'mesin_jalan' => 7,
                'aliasjarum' => 'Mc Topi 10inch (240N)',
            ],
            [
                'area' => 'KK8J',
                'jarum' => 'POM-POM',
                'total_mc' => 1,
                'brand' => 'GLOVES',
                'mesin_jalan' => 1,
                'aliasjarum' => 'Mc Fluff Ball',
            ]
        ];
        $this->db->table('data_mesin')->insertBatch($data);
    }
}
